### ISSUE TITLE
Bundle size gets ridiculously large

### ISSUE THREAD

**Issue by maziluradu** [johannesjo/angular-material-css-vars#168] opened 2024-03-30 21:36 UTC
## :frowning: Problem Statement

This library is incredibly helpful, however using it in my project increases the styles chunk size by about 200kb. As a reference, the original size of the "styles" chunk is ~90kb. Using this increases the size of the chunk to ~300kb. I would love to know whether there's any ongoing effort on reducing the size of the library.

## :grey_question: Possible Solution

Optimize the amount of SCSS code included into the bundle

## :arrow_heading_up: Describe alternatives you've considered

N/A

## :heavy_plus_sign: Additional context

N/A

**Comment by json-derulo** [comment] 2024-03-31 07:48
Hi! Thanks for opening the issue. You are comparing a bit apples with oranges. With a prebuilt theme, the CSS bundle will have roughly 90kB. However, a custom theme with both dark and light mode in plain Angular Material has 150kB.

Also in a fresh project using CSS vars I can't reproduce such high increases in bundle sizes. With the base setup, I'm getting a bundle size of 190kB (increase of 40kB). With disabled dark mode, the bundle size is 115kB (increase of 25kB). It would be helpful to share what exactly you are doing to see such high bundle sizes.

**Comment by json-derulo** [comment] 2024-04-09 11:31
Friendly reminder to provide the requested information, otherwise I will have to close this issue.

**Closed** 2024-04-23 12:12 UTC
Labels: needs clarification
